//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies
    {
        public byte id { get; set; }
        public string movieName { get; set; }
        public string movieInformation { get; set; }
        public string image { get; set; }
        public Nullable<byte> categoryId { get; set; }
    }
}
